<?php

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Liberu\Foundation\Organizations\Models\Team;
use Liberu\Foundation\RolesPermissions\Models\Role;

uses(RefreshDatabase::class);

// Super-admin visibility must come from Shield's gate, independently of the
// permission catalog generated by the application boot process.

it('defines the super admin via gate so it bypasses policies', function () {
    expect(config('filament-shield.super_admin.define_via_gate'))->toBeTrue();
});

it('lets a super_admin view resources even with no permissions generated', function () {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    setPermissionsTeamId($team->id);
    Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web', 'team_id' => $team->id]);
    $user->assignRole('super_admin');
    $user->unsetRelation('roles');

    expect($user->can('viewAny', User::class))->toBeTrue();
});
